# <center> <font color='green'> <b> NUMPY </b> </font> </center>

## Table of contents
- [1 - Import](#1)
- [2 - Indexing](#2)



<a name="1"></a>
## <b> <font color=' #16a085'> 1. Import </b> </font>

In [8]:
import numpy as np

<a name="2"></a>
## <b> <font color=' #16a085'> 2. Indexing and slicing </b> </font>

### 1D Arrays

In [25]:
x = np.arange(1,21)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [22]:
x[-4:] # last 4

array([17, 18, 19, 20])

In [33]:
# elements from the index 5 onwards
x[5:]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [27]:
x[3] # third element

4

In [28]:
# From the third element from the back, to the third element, with a step of -2; 
#it does not include the third element
x[-3:3:-2] 

array([18, 16, 14, 12, 10,  8,  6])

### 3D Arrays

A 3D array is like a stack of matrices:

- The first index, i, selects the matrix
- The second index, j, selects the row
- The third index, k, selects the column

<img src="images/3d_array.png"/>

In [10]:
# first dimension represents the slices within each layer


# first layer
print(a[0,:,:],"\n") # primera profundidad
print(a[0,:,:].shape) # 3 filas, 4 columnas



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

(3, 4)


<img src="images/first_layer.png"/>

In [14]:
# second layer
print(a[1,:,:],"\n") # primera profundidad
print(a[1,:,:].shape) # 3 filas, 4 columnas

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

(3, 4)


<img src="images/second_layer.png">

In [15]:
# second dimension (rows in each layer)

# first row of each layer
print(a[:,0,:],"\n")
print(a[:,0,:].shape) 

[[ 0  1  2  3]
 [12 13 14 15]] 

(2, 4)


<img src="images/first_row.png"/>

In [16]:
# second row of each layer

# third row of each layer
print(a[:,2,:],"\n")
print(a[:,2,:].shape) 

[[ 8  9 10 11]
 [20 21 22 23]] 

(2, 4)


<img src="images/third_row.png"/>

In [13]:

# third dimension (columns in each layer)

# first column of each layer
print(a[:,:,0],"\n")
print(a[:,:,0].shape) 



[[ 0  4  8]
 [12 16 20]] 

(2, 3)


<img src="images/first_column.png"/>

In [17]:
# second column of each layer
print(a[:,:,1],"\n")
print(a[:,:,1].shape) 

[[ 1  5  9]
 [13 17 21]] 

(2, 3)


<img src="images/second_column.png"/>

In [14]:
# second column of the first layer

print(a[0,:,1]) # first layer, all rows, second column
print(a[0,:,1].shape)

[1 5 9]
(3,)


<img src="images/second_col_first_layer.png"/>

In [17]:
# last 2 columns of each layer

print(a[:,:,2:]) 
print(a[:,:,2:].shape)

[[[ 2  3]
  [ 6  7]
  [10 11]]

 [[14 15]
  [18 19]
  [22 23]]]
(2, 3, 2)


<img src="images/last_two_cols.png"/>

In [18]:
# last row of first layer

print(a[0,-1,:]) 
print(a[0,-1,:].shape)

[ 8  9 10 11]
(4,)


<img src="images/last_row_first_layer.png"/>

In [35]:
a[...,0] # same as x[:,:,0]

array([[ 0,  4,  8],
       [12, 16, 20]])

In [36]:
a[0,...] # same as a[0,:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Each newaxis object in the selection tuple serves to expand the dimensions of the resulting selection by one unit-length dimension. The added dimension is the position of the newaxis object in the selection tuple. newaxis is an alias for None, and None can be used in place of this with the same result. From the above example:

In [87]:
print(x.shape)

x[:, np.newaxis, :, :].shape

(2, 3, 1)


(2, 1, 3, 1)